openapi: 3.0.4
info:
  version: '1.0'
  title: "SCUDO"
  description: API for SCUDO application
  license:
    name: MIT
servers:
  - url: http://127.0.0.1:3010/api/v1
    description: Localhost
  # TODO: Add production server
paths:
  # TODO: Define API endpoints