openapi: 3.0.4
info:
  version: "1.0"
  title: "SCUDO"
  description: API for SCUDO application
  license:
    name: MIT
servers:
  - url: http://127.0.0.1:3010/api/v1
    description: Localhost
  - url: https://scudo.tn.it/api/v1
    description: Staging server
  - url: https://scudo.ondrender.com/api/v1
    description: Production server
paths:
  /articles/:
    get:
      summary: Get all published articles
      tags:
        - Articles
      parameters:
        - in: query
          name: q
          schema:
            type: string
          description: Search articles by title or short_text or text
        - in: query
          name: category
          schema:
            type: string
          description: Filter articles by category
      responses:
        "200":
          description: A list of published articles of the guide
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    self:
                      type: string
                    id:
                      type: string
                    title:
                      type: string
                    img:
                      type: string
                    short_text:
                      type: string
                    categoria:
                      type: string
                    author:
                      type: object
                      $ref: "#/components/schemas/Author"
    post:
      summary: Create and publish a new article
      tags:
        - Articles
      security:
        - XAccessTokenHeaderAuth: []
        - TokenQueryAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                text:
                  type: string
                short_text:
                  type: string
                categoria:
                  type: string
                img:
                  type: string

      responses:
        "201":
          description: Article created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  self:
                    type: string
                  article:
                    type: object
                    $ref: "#/components/schemas/Article"
        "401":
          description: Missing token
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        "403":
          description: Invalid token or insufficient permissions
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
  /articles/{id}:
    get:
      summary: Get article by ID
      tags:
        - Articles
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Article details
          content:
            application/json:
              schema:
                type: object
                $ref: "#/components/schemas/Article"
        "400":
          description: Invalid article ID
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        "404":
          description: Article not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
    put:
      summary: Update an article by ID
      tags:
        - Articles
      security:
        - XAccessTokenHeaderAuth: []
        - TokenQueryAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                text:
                  type: string
                short_text:
                  type: string
                categoria:
                  type: string
                img:
                  type: string

      responses:
        "200":
          description: Article updated successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  article:
                    type: object
                    $ref: "#/components/schemas/Article"
        "400":
          description: Invalid article ID
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        "401":
          description: Missing token
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        "403":
          description: Invalid token or insufficient permissions
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        "404":
          description: Article not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
    delete:
      summary: Delete an article by ID
      tags:
        - Articles
      security:
        - XAccessTokenHeaderAuth: []
        - TokenQueryAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        "204":
          description: Article deleted successfully
        "400":
          description: Invalid article ID
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        "401":
          description: Missing token
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        "403":
          description: Invalid token or insufficient permissions
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        "404":
          description: Article not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
  /articles/draft:
    post:
      summary: Create and a new article and save it as draft
      tags:
        - Articles
      security:
        - XAccessTokenHeaderAuth: []
        - TokenQueryAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                text:
                  type: string
                short_text:
                  type: string
                categoria:
                  type: string
                img:
                  type: string

      responses:
        "201":
          description: Article created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  self:
                    type: string
                  article:
                    type: object
                    $ref: "#/components/schemas/Article"
        "401":
          description: Missing token
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        "403":
          description: Invalid token or insufficient permissions
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
  /articles/publish/{id}:
    put:
      summary: Publish a draft article by ID
      tags:
        - Articles
      security:
        - XAccessTokenHeaderAuth: []
        - TokenQueryAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Article published successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  self:
                    type: string
                  article:
                    type: object
                    $ref: "#/components/schemas/Article"
        "400":
          description: Invalid article ID
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        "401":
          description: Missing token
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        "403":
          description: Invalid token or insufficient permissions
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        "404":
          description: Article not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
  /operators:
    get:
      summary: Get all operators
      tags:
        - Operators
      security:
        - XAccessTokenHeaderAuth: []
        - TokenQueryAuth: []
      parameters:
        - in: query
          name: q
          schema:
            type: string
          description: Search operators by name or surname
        - in: query
          name: orderby
          schema:
            type: string
            enum: ["name", "surname", "role"]
          description: Order operators by specified field
        - in: query
          name: order
          schema:
            type: string
            enum: ["asc", "desc"]
          description: Order direction
      responses:
        "200":
          description: A list of operators
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  $ref: "#/components/schemas/Operator"
        "401":
          description: Missing token
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        "403":
          description: Invalid token or insufficient permissions
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
    post:
      summary: Create a new operator
      tags:
        - Operators
      security:
        - XAccessTokenHeaderAuth: []
        - TokenQueryAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                surname:
                  type: string
                email:
                  type: string
                role:
                  type: string
                  enum: ["reporter", "editor", "admin"]
                password:
                  type: string
      responses:
        "201":
          description: Operator created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  self:
                    type: string
        "400":
          description: Invalid input data
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        "401":
          description: Missing token
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        "403":
          description: Invalid token or insufficient permissions
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        "409":
          description: Operator with the given email already exists
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
  /auth/operator/login/:
    post:
      summary: Operator login and obtain JWT token
      tags:
        - Authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
      responses:
        "200":
          description: Login successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  token:
                    type: string
                  id:
                    type: string
                  self:
                    type: string
        "400":
          description: Invalid body
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        "401":
          description: Invalid email or password
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        "403":
          description: Operator account is inactive
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string

components:
  securitySchemes:
    XAccessTokenHeaderAuth: # arbitrary name for the security scheme
      description: >-
        The API authentication.
        The API key must be passed in the header 'x-access-token'.
        The API key must be a valid JWT token.
      type: apiKey
      in: header
      name: x-access-token

    TokenQueryAuth: # arbitrary name for the security scheme
      description: >-
        The API authentication.
        The API key must be passed in the query string 'token'.
        The API key must be a valid JWT token.
      type: apiKey
      in: query
      name: token

  schemas:
    Article:
      type: object
      required:
        - title
        - text
        - author
        - short_text
        - categoria
      properties:
        _id:
          type: string
          description: "ID of the article"
        title:
          type: string
          description: "Title of the article"
        text:
          type: string
          description: "Full text of the article"
        img:
          type: string
          description: "Image filename associated with the article"
        author:
          type: object
          $ref: "#/components/schemas/Author"
        last_edit:
          type: string
          format: date-time
          description: "Date of the last edit of the article"
        isDraft:
          type: boolean
          description: "Indicates whether the article is a draft (not published) or published"
        short_text:
          type: string
          description: "Short text of the article"
        categoria:
          type: string
          description: "Category of the article"

    Author:
      type: object
      required:
        - _id
        - name
        - surname
      properties:
        _id:
          type: string
          description: "ID of the author"
        name:
          type: string
          description: "Name of the author"
        surname:
          type: string
          description: "Surname of the author"
    Operator:
      type: object
      required:
        - name
        - surname
        - email
        - role
        - isActive
      properties:
        name:
          type: string
          description: "Name of the operator"
        surname:
          type: string
          description: "Surname of the operator"
        email:
          type: string
          description: "Email of the operator"
        role:
          type: string
          enum: ["reporter", "editor", "admin"]
          description: "Role of the operator"
        isActive:
          type: boolean
          description: "Indicates whether the operator is active or not"
    Report:
    Communication:
